#ifndef D2DGBA_BUILD_INFO_H
#define D2DGBA_BUILD_INFO_H

#define D2DGBA_BUILD_VERSION ""
#define D2DGBA_BUILD_COMMIT ""
#define D2DGBA_BUILD_STRING (D2DGBA_BUILD_VERSION "+" D2DGBA_BUILD_COMMIT)
#define D2DGBA_BUILD_DATE ""
#define D2DGBA_BUILD_HOST_OS ""
#define D2DGBA_BUILD_HOST_ENV ""
#define D2DGBA_BUILD_COMPILER ""

#endif //D2DGBA_BUILD_INFO_H
