#!/usr/bin/env python3
"""
Extract Doom2D sound lumps (DS*) from a WAD and save as 8-bit PCM WAV files.

Sounds in doom2d WAD are raw 8-bit PCM, 11025 Hz, mono (no header in lump).
Output: WAV files with correct headers in a directory.
"""

import argparse
import os
import sys

# Allow importing from tools/imports when run from project root or tools/
_TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
if _TOOLS_DIR not in sys.path:
    sys.path.insert(0, _TOOLS_DIR)

from imports.wadfile import WadFile


SAMPLE_RATE = 11025
CHANNELS = 1
BITS_PER_SAMPLE = 8


def _sound_short_name(lump_name: str) -> str:
    """Strip DS prefix for display/ref; game uses name without DS (e.g. TELEPT)."""
    return lump_name[2:] if lump_name.startswith("DS") else lump_name


def _sound_item_id(lump_name: str) -> str:
    """C++ identifier for bn::sound_items::xxx (lowercase with ds prefix, e.g. dstelept)."""
    return lump_name.lower()


# Original formula: length = lump_size_bytes / 605 (from F_getreslen(...)/605)
LENGTH_DIVISOR = 605


def write_sound_ref_cpp(lumps: list, out_path: str) -> None:
    """Generate get_pcm_ref() body only: if/return lines and BN_ERROR. Include into pcm_ref_t get_pcm_ref(...)."""
    lines = [
        "// Generated by dmsnd2wav.py - do not edit",
        "",
    ]
    for _, name, data in lumps:
        short = _sound_short_name(name)
        ident = _sound_item_id(name)
        length = len(data) // LENGTH_DIVISOR
        lines.append(f'    if (name_equals(sound_name, "{name}")) return {{ &bn::sound_items::{ident}, {length} }};')
    lines.append('    BN_ERROR("get_pcm_ref: unknown sound name", sound_name);')
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def write_wav(path: str, pcm_data: bytes) -> None:
    """Write 8-bit unsigned PCM mono to a WAV file.

    Doom2D WAD stores 8-bit signed PCM (0 = silence, -128..127). WAV 8-bit is
    unsigned (128 = silence, 0..255). We convert signed -> unsigned only;
    no gain/amplification.
    """
    # signed 8-bit -> unsigned 8-bit for WAV: out = (in + 128) & 0xFF
    samples = bytes((b + 128) & 0xFF for b in pcm_data)
    n = len(samples)
    byte_rate = SAMPLE_RATE * CHANNELS * (BITS_PER_SAMPLE // 8)
    block_align = CHANNELS * (BITS_PER_SAMPLE // 8)
    data_chunk_size = n
    riff_data_size = 4 + 24 + 8 + data_chunk_size
    riff_file_size = 4 + riff_data_size

    with open(path, "wb") as f:
        f.write(b"RIFF")
        f.write((riff_file_size).to_bytes(4, "little"))
        f.write(b"WAVE")
        f.write(b"fmt ")
        f.write((16).to_bytes(4, "little"))
        f.write((1).to_bytes(2, "little"))  # PCM
        f.write((CHANNELS).to_bytes(2, "little"))
        f.write((SAMPLE_RATE).to_bytes(4, "little"))
        f.write((byte_rate).to_bytes(4, "little"))
        f.write((block_align).to_bytes(2, "little"))
        f.write((BITS_PER_SAMPLE).to_bytes(2, "little"))
        f.write(b"data")
        f.write((data_chunk_size).to_bytes(4, "little"))
        f.write(samples)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Extract Doom2D DS* sound lumps from a WAD to WAV files."
    )
    default_wad = os.path.normpath(os.path.join(_TOOLS_DIR, "..", "input", "doom2d.wad"))
    parser.add_argument(
        "wad",
        nargs="?",
        default=None,
        help=f"Path to WAD file (default: {default_wad})",
    )
    parser.add_argument(
        "-o",
        "--output",
        default="sounds",
        help="Output directory for WAV files (default: sounds)",
    )
    parser.add_argument(
        "-l",
        "--list",
        action="store_true",
        help="Only list DS* lumps, do not extract",
    )
    args = parser.parse_args()

    wad_path = args.wad or default_wad
    if not os.path.isabs(wad_path):
        wad_path = os.path.normpath(os.path.join(os.getcwd(), wad_path))
    if not os.path.isfile(wad_path):
        print(f"Error: WAD file not found: {wad_path}", file=sys.stderr)
        return 1

    try:
        wad = WadFile.from_path(wad_path)
    except Exception as e:
        print(f"Error: failed to read WAD: {e}", file=sys.stderr)
        return 1

    lumps = wad.lumps_by_prefix("DS")
    if not lumps:
        print("No lumps starting with 'DS' found in WAD.", file=sys.stderr)
        return 1

    if args.list:
        for idx, name, data in lumps:
            print(f"{name}\tindex={idx}\tsize={len(data)}")
        return 0

    out_dir = args.output
    os.makedirs(out_dir, exist_ok=True)
    for idx, name, data in lumps:
        short = _sound_short_name(name)
        wav_name = name.lower() + ".wav"
        out_path = os.path.join(out_dir, wav_name)
        write_wav(out_path, data)
        print(f"Written {out_path} ({len(data)} samples)")
    ref_path = os.path.join(out_dir, "sound_ref.cpp.inc")
    write_sound_ref_cpp(lumps, ref_path)
    print(f"Written {ref_path} (get_pcm_ref)")
    print(f"Extracted {len(lumps)} sound(s) to {out_dir}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
